//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class exchangeRate
    {
        public string SiteUpdated { get; set; }
        public int bankId { get; set; }
        public string bankName { get; set; }
        public string ADBR { get; set; }
        public string ADSR { get; set; }
        public string EUBR { get; set; }
        public string EUSR { get; set; }
        public string NORBR { get; set; }
        public string NORSR { get; set; }
        public string USBR { get; set; }
        public string USSR { get; set; }
    }
}
